version: 2
jobs:
  build:
    docker:
      - image: jtredoux/node-aws:latest

    working_directory: ~/cra-ci-demo

    steps:
      - checkout
      
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run: 
        - npm install
        - npm run build

      - persist_to_workspace:
        root: .
        path:
        -built/*
   
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    

