version: 2 #uses CircleCI 2.0
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      #Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch}}--{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

      
      -run: yarn build