
version: 2 #uses CircleCI 2.0

  jobs:
    build:
      #working_directory: ~/repo
      docker:
        - image: 'circleci/node:8'
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: 
            name:     Install dependenies with npm
            command:  npm install

        - save_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
            paths:
              - node_modules
              
        - run: 'yarn test'


workflow:
  version: 2
  Build: 
    jobs:
      - build