version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      environment:
      AWS_REGION: europe-west-2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    requires:
      - build
      - aws-s3/sync:
            from: dist
            to: 'http://www.chillax-app.net.s3-website.eu-west-2.amazonaws.com/'
            arguments: |
              --acl public-read 
              --cache-control "max-age=86400" 
            overwrite: true

workflows:
  version: 2
  workflow:
    jobs:
    - build:        
        filters:
          branches:
            only: master

    - deploy:
        filters:
          branches:
            only: master