
version: 2 #uses CircleCI 2.0

  jobs:
    build:
      #working_directory: ~/repo
      docker:
        - image: 'circleci/node:8'
      steps:
        - run: 
          name:     Install dependenies with npm
          command:  npm install
        - checkout
        - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
          - node_modules
        - restore_cache:
            keys:
              - v1-dependencies-{{ arch}}--{{ checksum "package.json" }}
              - v1-dependencies-

workflow:
  version: 2
  Build: 
    jobs:
      - build